/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.builder.exemplo;

import javax.swing.JOptionPane;

/**
 *
 * @author tiluc
 */
public class ProdutoCadastro extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoCadastro
     */
    public ProdutoCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoEstado = new javax.swing.ButtonGroup();
        AreaDeBoasVindas = new javax.swing.JPanel();
        TextoDeBoasVindas = new javax.swing.JLabel();
        TextoDeFeedback = new javax.swing.JLabel();
        BotaoSair = new javax.swing.JButton();
        Formulario = new javax.swing.JPanel();
        NomeTexto = new javax.swing.JLabel();
        NomeCampo = new javax.swing.JTextField();
        EstadoTexto = new javax.swing.JLabel();
        EstadoNovo = new javax.swing.JRadioButton();
        EstadoUsado = new javax.swing.JRadioButton();
        PrecoTexto = new javax.swing.JLabel();
        PrecoCampo = new javax.swing.JTextField();
        QuantidadeTexto = new javax.swing.JLabel();
        QuantidadeCampo = new javax.swing.JTextField();
        CategoriaTexto = new javax.swing.JLabel();
        CategoriaComboBox = new javax.swing.JComboBox<>();
        SalvarBotao = new javax.swing.JButton();
        AreaDeFeedback = new javax.swing.JPanel();
        Feedback = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        NomeFeedback = new javax.swing.JLabel();
        EstadoFeedback = new javax.swing.JLabel();
        PrecoFeedback = new javax.swing.JLabel();
        QuantidadeFeedback = new javax.swing.JLabel();
        CategoriaFeedback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextoDeBoasVindas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextoDeBoasVindas.setText("Cadastro de Produtos");

        TextoDeFeedback.setText("Preencha os campos abaixo corretamente para cadastrar um produto:");

        BotaoSair.setText("Sair");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AreaDeBoasVindasLayout = new javax.swing.GroupLayout(AreaDeBoasVindas);
        AreaDeBoasVindas.setLayout(AreaDeBoasVindasLayout);
        AreaDeBoasVindasLayout.setHorizontalGroup(
            AreaDeBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaDeBoasVindasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AreaDeBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AreaDeBoasVindasLayout.createSequentialGroup()
                        .addComponent(TextoDeFeedback)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AreaDeBoasVindasLayout.createSequentialGroup()
                        .addComponent(TextoDeBoasVindas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoSair)))
                .addContainerGap())
        );
        AreaDeBoasVindasLayout.setVerticalGroup(
            AreaDeBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaDeBoasVindasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AreaDeBoasVindasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoDeBoasVindas)
                    .addComponent(BotaoSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(TextoDeFeedback)
                .addContainerGap())
        );

        NomeTexto.setLabelFor(NomeCampo);
        NomeTexto.setText("Nome:");

        NomeCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCampoActionPerformed(evt);
            }
        });

        EstadoTexto.setText("Estado:");

        GrupoEstado.add(EstadoNovo);
        EstadoNovo.setText("Novo");
        EstadoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoNovoActionPerformed(evt);
            }
        });

        GrupoEstado.add(EstadoUsado);
        EstadoUsado.setText("Usado");

        PrecoTexto.setText("Preço (R$):");

        QuantidadeTexto.setText("Quantidade:");

        CategoriaTexto.setText("Categoria:");

        CategoriaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção:", "Placa Mãe", "Processador (CPU)", "Memória Ram", "Armazenamento (HD/SSD)", "Placa de Vídeo (GPU)", "Gabinetes", "Periféricos" }));

        SalvarBotao.setText("Salvar");
        SalvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormularioLayout = new javax.swing.GroupLayout(Formulario);
        Formulario.setLayout(FormularioLayout);
        FormularioLayout.setHorizontalGroup(
            FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeTexto)
                    .addComponent(NomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FormularioLayout.createSequentialGroup()
                        .addComponent(EstadoTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EstadoNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EstadoUsado)))
                .addGap(26, 26, 26)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormularioLayout.createSequentialGroup()
                        .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecoTexto)
                            .addComponent(PrecoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuantidadeCampo)
                            .addGroup(FormularioLayout.createSequentialGroup()
                                .addComponent(QuantidadeTexto)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormularioLayout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SalvarBotao)
                            .addComponent(CategoriaTexto))
                        .addGap(18, 18, 18)
                        .addComponent(CategoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        FormularioLayout.setVerticalGroup(
            FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormularioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeTexto)
                    .addComponent(PrecoTexto)
                    .addComponent(QuantidadeTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantidadeCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstadoTexto)
                    .addComponent(CategoriaTexto)
                    .addComponent(CategoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EstadoNovo)
                    .addComponent(EstadoUsado))
                .addGap(18, 18, 18)
                .addComponent(SalvarBotao)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        AreaDeFeedback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Feedback.setText("Obs.: Você será notificado aqui se o produto foi cadastrado com sucesso ou não.");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NomeFeedback.setText("Nome: ");

        EstadoFeedback.setText("Estado:");

        PrecoFeedback.setText("Preço:");

        QuantidadeFeedback.setText("Quantidade:");

        CategoriaFeedback.setText("Categoria:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrecoFeedback)
                    .addComponent(NomeFeedback)
                    .addComponent(EstadoFeedback))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CategoriaFeedback)
                    .addComponent(QuantidadeFeedback))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecoFeedback)
                    .addComponent(QuantidadeFeedback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstadoFeedback)
                    .addComponent(CategoriaFeedback))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout AreaDeFeedbackLayout = new javax.swing.GroupLayout(AreaDeFeedback);
        AreaDeFeedback.setLayout(AreaDeFeedbackLayout);
        AreaDeFeedbackLayout.setHorizontalGroup(
            AreaDeFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaDeFeedbackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AreaDeFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Feedback)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        AreaDeFeedbackLayout.setVerticalGroup(
            AreaDeFeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaDeFeedbackLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Feedback)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AreaDeBoasVindas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Formulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(AreaDeFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AreaDeBoasVindas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AreaDeFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void NomeCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCampoActionPerformed

    private void EstadoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoNovoActionPerformed

    private void SalvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBotaoActionPerformed
        // TODO add your handling code here:
        
        Produto p = new Produto();
        p.setNome(NomeCampo.getText());
        p.setPreco( Double.parseDouble(PrecoCampo.getText()));
        p.setQuantidade(Integer.parseInt(QuantidadeCampo.getText()));
        
        if (EstadoNovo.isSelected()){
            p.setEstado("Novo");
        } else if (EstadoUsado.isSelected()) {
            p.setEstado("Usado");
        }
        
        p.setCategoria(CategoriaComboBox.getSelectedItem().toString());
        
        JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
        
        Feedback.setText("O seguinte produto foi cadastrado:");
        NomeFeedback.setText("Nome: " + p.getNome());
        PrecoFeedback.setText("Preço: " + p.getPreco());
        QuantidadeFeedback.setText("Quantidade: " + p.getQuantidade());
        EstadoFeedback.setText("Estado: " + p.getEstado());
        CategoriaFeedback.setText("Categoria: " + p.getCategoria());
        
        
    }//GEN-LAST:event_SalvarBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaDeBoasVindas;
    private javax.swing.JPanel AreaDeFeedback;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JComboBox<String> CategoriaComboBox;
    private javax.swing.JLabel CategoriaFeedback;
    private javax.swing.JLabel CategoriaTexto;
    private javax.swing.JLabel EstadoFeedback;
    private javax.swing.JRadioButton EstadoNovo;
    private javax.swing.JLabel EstadoTexto;
    private javax.swing.JRadioButton EstadoUsado;
    private javax.swing.JLabel Feedback;
    private javax.swing.JPanel Formulario;
    private javax.swing.ButtonGroup GrupoEstado;
    private javax.swing.JTextField NomeCampo;
    private javax.swing.JLabel NomeFeedback;
    private javax.swing.JLabel NomeTexto;
    private javax.swing.JTextField PrecoCampo;
    private javax.swing.JLabel PrecoFeedback;
    private javax.swing.JLabel PrecoTexto;
    private javax.swing.JTextField QuantidadeCampo;
    private javax.swing.JLabel QuantidadeFeedback;
    private javax.swing.JLabel QuantidadeTexto;
    private javax.swing.JButton SalvarBotao;
    private javax.swing.JLabel TextoDeBoasVindas;
    private javax.swing.JLabel TextoDeFeedback;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
